#@ load("@ytt:data", "data")

apiVersion: gemfire.tanzu.vmware.com/v1
kind: GemFireCluster
metadata:
    name: #@ data.values.cluster_name
spec:
    image:    #@ data.values.image
    servers:  #@ data.values.servers
    replicas: #@ data.values.replicas