#@ load("@ytt:data", "data")

apiVersion: gemfire.vmware.com/v1
kind: GemFireCluster
metadata:
    name: #@ data.values.cluster_name
spec:
    image: #@ data.values.image
    antiAffinityPolicy: #@ data.values.anti_affinity_policy
#@ if data.values.ingress_gateway_name != "":
    ingress:
        gatewayName: #@ data.values.ingress_gateway_name
#@ end
    resourceManager:
#@ if data.values.critical_heap_percentage > 0:
        criticalHeapPercentage: #@ data.values.critical_heap_percentage
#@ end
#@ if data.values.eviction_heap_percentage > 0:
        evictionHeapPercentage: #@ data.values.eviction_heap_percentage
#@ end
    serialization:
        pdx:            
            readSerialized: #@ data.values.enable_pdx
    security:
#@ if data.values.tls_secret_name!= "":
        tls:
            secretName: #@ data.values.tls_secret_name
            clientAuthenticationRequired: true
#@ end
    locators:
        replicas: #@ data.values.locators
    servers:
        libraries:
            - name: gemfire-for-redis-apps
              container:
                    image: registry.tanzu.vmware.com/tanzu-gemfire-for-redis-apps/gemfire-for-redis-apps:1.0.1
                    path: "/gemfire-for-redis-apps/*"
                    imagePullSecretRef:
                        name: image-pull-secret
        overrides:
            gemFireProperties:
                - name : "start-dev-rest-api"
                  value : "true"
            jvmOptions: ["-Dgemfire-for-redis-enabled=true"]

