#@ load("@ytt:data", "data")

apiVersion: gemfire.tanzu.vmware.com/v1
kind: GemFireCluster
metadata:
    name: #@ data.values.cluster_name
spec:
    image:    #@ data.values.image
    servers:  #@ data.values.servers
    replicas: #@ data.values.replicas
    #@ if data.values.persistent == 1:
    persistence:
        storageClassName: #@ data.values.storageclassname
        storage: #@ data.values.storage
    #@ end
    resources:
        requests:
        cpu: #@ data.values.cpu
        memory: #@ data.values.memory
        limits:
        cpu: #@ data.values.cpu
        memory: #@ data.values.memory