---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: gemfire-contour-gateway-class
spec:
  controllerName: projectcontour.io/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gemfire-gateway
spec:
  gatewayClassName: gemfire-contour-gateway-class
  listeners:
  - name: gemfire-gateway-listener
    protocol: TLS
    port: 9000
    tls:
      mode: Passthrough